### PR TITLE
feat: enhance readme

### PR DESCRIPTION
**Pull request by mtwente**
# Pull request

## Proposed changes

- add slightly more details on how to use this template

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **Documentation**
	- Updated and expanded the instructions for using the Quarto template in the `README.md`, including steps for editing, installing Quarto, previewing, enhancing the abstract, and publishing on GitHub Pages.

### CODE REVIEW

**Comment by mtwente** [comment]
I also created a slightly longer sample abstract (made by ChatGPT) to illustrate how it will look like in the end: https://mtwente.github.io/abstract-template/

**Comment by maehr** [comment]
> I also created a slightly longer sample abstract (made by ChatGPT) to illustrate how it could look like in the end: https://mtwente.github.io/abstract-template/

I like it. Why not merge it into the template?

**Review by maehr — CHANGES_REQUESTED** [review]
The changes already help. Please add the reworked template as well. Thanks a bunch

**Comment by maehr** [comment]
I reworked the Readme even more. Check out https://github.com/digihistch24/abstract-template/pull/6

**Comment by maehr** [comment]
@mtwente may I close this PR due to #6 ?

**Pull request closed without merging**
